[project]
name = "gsl-forecast"
version = "0.1.0"
description = "Forecasting the Great Salt Lake's depth"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "duckdb>=1.2.0",
    "experiment-tracker",
    "pandas>=2.2.3",
    "pytest>=8.3.4",
    "requests>=2.32.3",
]

[tool.pytest.ini_options]
testpaths = ["tests"]

[tool.uv.sources]
experiment-tracker = { git = "https://github.com/jcblsn/experiment-tracker.git", rev = "main" }

[dependency-groups]
dev = [
    "ipykernel>=6.29.5",
]
